### ISSUE TITLE
Import error: no module called lsst.sims!

### ISSUE THREAD

**Issue by drphilmarshall** [LSST-nonproject/sims_maf_contrib#10]
Has something changed in the way the lsst python module works? The time delay examples notebook tries to do

    import lsst.sims.maf.db as db

but this causes me the following error:

    ImportError: No module named sims.maf.db

This is after doing the usual loadLSST.csh, making sure I am using Anaconda python, etc. BTW ipython tells me that the only packages available in `lsst` are `lsst.pkgutil` and `lsst.sconsUtils`.

**Comment by rhiannonlynne** [comment]
Can you please confirm you did a "setup sims_maf -t sims" after load lsst?

**Comment by drphilmarshall** [comment]
Resolved in #11
