### ISSUE TITLE
Time Delay Cosmography example needs illustrating!

### ISSUE THREAD

**Issue by drphilmarshall** [LSST-nonproject/sims_maf_contrib#11]
Hi Lynne!  

I'm making wiki pages to help me present our work on the strong lens time delay metrics to the DESC collaboration at our meeting this week. Unfortunately I can't reproduce your nice results, because of the error in #10 - would you mind pasting in the accuracy, precision and fraction plots from your notebook, please? I was thinking it'd be nice to show the skymap on the left and the histogram on the right in each case - and we're only interested in the "multi" filter results, I think. What do you think? Thanks! :-)

**Comment by drphilmarshall** [comment]
BTW the wiki page Im talking about is [this one](https://github.com/LSST-nonproject/sims_maf_contrib/wiki/Time-Delay-Lens-Cosmography) :-)

**Comment by rhiannonlynne** [comment]
Hi Phil, 

Happy to do this for you - I'm home with sick kiddo today, but will get it done soon as possible. 
Did you check if the notebook works (or not) if you do 
'setup sims_maf -t sims' 
and 'setup sims_maf_contrib' ? 
Also, can you grab them from the URL if you put it into nbviewer? 
(but yes, I'll regenerate them!)

Lynne

**Comment by drphilmarshall** [comment]
That does it! I'll make a note to always run these commands... Thanks Lynne!

**Comment by rhiannonlynne** [comment]
Nice wiki page :)
