### ISSUE TITLE
Clean maf_contrib classes

### ISSUE THREAD

**Issue by rhiannonlynne** [LSST-nonproject/sims_maf_contrib#29]
Some of the metrics in maf_contrib clash with names in the base metrics. 
Also, some of the metrics/stackers should be moved into core maf. 
Minor code standards, like line length and comments, should be addressed too. 

The simpler this work is, the less likely it is to cause conflicts for users -- it'd be great to get some feedback from users to know what we can move / what that might break.

**Comment by tanguita** [comment]
Hi @rhiannonlynne, 

I am having some issues with some of the movements. In particular with this:

"from lsst.sims.maf.stackers import BaseStacker, SeasonStacker"

It seems that lsst.sims.maf.stackers (latest installed with conda) does not have the SeasonStacker previously found in mafContrib.SeasonStacker_v2

Everytime I import mafContrib I get an error then:

---> 16 from lsst.sims.maf.stackers import BaseStacker, SeasonStacker
ImportError: cannot import name SeasonStacker

**Comment by rhiannonlynne** [comment]
Sorry - I saw your comment, but only just getting a chance to address it. 
I'm not sure what's going on here and I can't reproduce it. Can you do 'conda list sims-maf' to send me the version number you have of MAF? The SeasonStacker should be there and available from lsst.sims.maf.stackers, even in version 2.2.1 (the latest from conda, although there should be a 2.2.3 release this week). 
What is the error you see when you import mafContrib?

**Comment by tanguita** [comment]
Hi, 

I seem to have an old version:
lsst-sims-maf             2.0.1.5.post6         a2083a4_0   
I just realized I am using this repository:  http://research.majuric.org/conda/stable
instead of this one: http://eupsforge.net/conda/dev which indeed has version 2.2.1

I don't know when and why I added that repository. I'm reinstalling now.

Thanks!
