### ISSUE TITLE
GRBTransientMetric

### ISSUE THREAD

**Issue by ebellm** [LSST-nonproject/sims_maf_contrib#30]
The existing GRBTrans notebook contains lightcurve parameters which are quite unphysical.  I have created a new metric, GRBTransientMetric, that subclasses TransientMetric but implements a more appropriate t^-\alpha decay.  I updated the GRBTrans metric throughout using this new metric.  The analysis will appear in the GRB science section of the whitepaper.

**Comment by rhiannonlynne** [comment]
Nice, thank you.
