### ISSUE TITLE
White dwarf colors in MAF

### ISSUE THREAD

**Issue by yoachim** [LSST-nonproject/sims_maf_contrib#33]
Hey @keatonb, I hear you would like some WD stars included in MAF.  Right now we've just got some basic OBAFGKM colors in here: https://github.com/lsst/sims_maf/blob/master/python/lsst/sims/maf/utils/stellarMags.py

It looks like we have a pretty big pile of regular and He WD stars in the sims_sed_library. Let me know what would be useful and I can compute the LSST colors and add them as options in MAF.

**Comment by keatonb** [comment]
That would be incredibly useful @yoachim !

Of course, WDs change colors significantly with temperature (and mass, to a lesser extent). Is it possible for us to access temperature-dependent colors through MAF?  

You may find some useful color information at http://www.astro.umontreal.ca/~bergeron/CoolingModels/

This assistance will help greatly in our getting some MAF metrics in place within the month for the Observing Strategy White Paper.

Thank you.

**Comment by yoachim** [comment]
yeah, we have a huge library of Bergeron model SEDs already in the sims framework.  If you just want a few representative ones, I can compute the colors and have those available in MAF. If you want really fine control, we can compute the colors at run-time.  That would add sims_sed_library as a dependency to MAF, so that might mean we'd keep the new code in the sims_maf_contrib repo, but whatever. 

lmk if you have a metric started somewhere so I can peek at it to see what might work best.

**Comment by keatonb** [comment]
I haven't had a chance to start a metric like this yet.

I think for starters, we could make good use of some representative models.  In particular, He WDs (DBs) at 25,000 K (DBV instability strip), regular H WDs (DAs) at 11,000 K (DAV instability strip), and DA WDS at 3000 K (faintest end of the WD luminosity function).  All of these at the average ~0.6 M_Sun.

In the future we may find use for finer control, but this should suffice for our initial work for the the Cadence White Paper.

Thanks again!
