### ISSUE TITLE
rotTelPos not in columnMap

### ISSUE THREAD

**Issue by jmeyers314** [LSST-nonproject/sims_maf_contrib#40]
I'm trying to investigate the AngularSpreadMetric contributed here on the distribution of camera rotator angles with respect to zenith.  [This website](https://confluence.lsstcorp.org/display/SIM/Summary+Table+Column+Descriptions) leads me to believe that this should be as simple as replacing the `rotSkyPos` argument in the Angular Spread jupyter notebook in this repo (which runs fine) with `rotTelPos`.  When I try this though, I get the error 'rotTelPos not in columnMap'.  

I suppose this is because one can easily compute `rotTelPos` from `rotSkyPos` and the parallactic angle `PA`, but I haven't been able to find the appropriate Stacker so far.  Does it exist?  or am I on the wrong track entirely?

**Comment by rhiannonlynne** [comment]
Hi Josh,

rotTelPos looks like it is actually in the current summary table (I think
there may have been a brief period where it wasn't), so this should work.
Can you check your capitalization? The column names are case sensitive.
If that doesn't work, just double check..
Open the file with sqlite and do a query to check rotTelPos is available in
the summary table, like :

> sqlite3 minion_1016_sqlite.db

> select rotTelPos from summary limit 1;

- Lynne

**Comment by jmeyers314** [comment]
Thanks Lynne,
I was still on enigma_1189.  After upgrading to minion_1016 everything works.  Closing this issue.
-Josh
