### ISSUE TITLE
RMS values not greater than Mean values

### ISSUE THREAD

**Issue by MeganNewsome** [LSST-nonproject/sims_maf_contrib#51]
My team and I have noticed that in any notebooks where "bundle.summaryValues()" is run, the subsequent Rms and Mean values listed show a mean that is greater than the RMS. Isn't RMS supposed to be larger than the mean by definition? We've tried to look into the code that goes into the bundle metric and summary metrics but can't find where these values are produced. We're not sure if it's a problem with the way these tutorial and test notebooks are run or if it's a problem with the metrics themselves. Anyone else have this problem or have some insight?

**Comment by yoachim** [comment]
Maybe we're using sloppy physics language. I think we use RMS == standard deviation. So it will depend on the distribution if mean or standard deviation is larger.
