### ISSUE TITLE
Confusing comment in Introduction.ipynb

### ISSUE THREAD

**Issue by michaelaye** [LSST-nonproject/sims_maf_contrib#58]
Cell [5] says:

```python
# Note the V3 for opening opsim version 3.x databases.
# Use V4 for more recent runs.
```
but the code afterwards is:
```python
opsdb = db.OpsimDatabase('baseline2018a.db')
outDir = 'output_directory'
resultsDb = db.ResultsDb(outDir=outDir)
```
so there's no mentioning of V3 or V4? Obsolete comment?

**Comment by rhiannonlynne** [comment]
Thanks for having a look at this (so long ago now). We have updated all of our notebooks and moved lsst_sims / sims_maf into a new conda-installable package called rubin_sim now.
The equivalent notebook is at https://github.com/lsst/rubin_sim_notebooks/blob/main/maf/tutorial/01_Introduction_to_MAF.ipynb and hopefully less confusing.
